### ISSUE TITLE
kotlin.KotlinNullPointerException Error in info.journeymap.tools.models.Dimension.<init>(Dimension.kt:17)

### ISSUE THREAD

**Issue by Utlamo** [TeamJM/journeymap-tools#7]
Error on start exe/jar file and display:
`kotlin.KotlinNullPointerException
	at info.journeymap.tools.models.Dimension.<init>(Dimension.kt:17)
	at info.journeymap.tools.models.World.<init>(World.kt:12)
	at info.journeymap.tools.models.MinecraftDirectory.getWorlds(MinecraftDirectory.kt:85)
	at info.journeymap.tools.models.MinecraftDirectory.loadData(MinecraftDirectory.kt:59)
	at info.journeymap.tools.models.MinecraftDirectory$1.invoke(MinecraftDirectory.kt:42)
	at info.journeymap.tools.models.MinecraftDirectory$1.invoke(MinecraftDirectory.kt:10)
	at tornadofx.LibKt$onChange$$inlined$apply$lambda$1.changed(Lib.kt:244)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at info.journeymap.tools.controllers.MainController.updateMinecraftDirectory(MainController.kt:150)
	at info.journeymap.tools.controllers.MainController.<init>(MainController.kt:123)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at tornadofx.FXKt.find(FX.kt:410)
	at info.journeymap.tools.views.MainView$$special$$inlined$inject$1.getValue(Component.kt:1197)
	at info.journeymap.tools.views.MainView$$special$$inlined$inject$1.getValue(Component.kt:173)
	at info.journeymap.tools.views.MainView.getController(MainView.kt)
	at info.journeymap.tools.views.MainView$root$1$1.invoke(MainView.kt:33)
	at info.journeymap.tools.views.MainView$root$1$1.invoke(MainView.kt:18)
	at tornadofx.LayoutsKt.hbox(Layouts.kt:384)
	at tornadofx.LayoutsKt.hbox$default(Layouts.kt:96)
	at info.journeymap.tools.views.MainView$root$1.invoke(MainView.kt:27)
	at info.journeymap.tools.views.MainView$root$1.invoke(MainView.kt:18)
	at tornadofx.LayoutsKt.vbox(Layouts.kt:388)
	at tornadofx.LayoutsKt.vbox$default(Layouts.kt:103)
	at info.journeymap.tools.views.MainView.<init>(MainView.kt:22)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at tornadofx.FXKt.find(FX.kt:410)
	at tornadofx.FXKt.find$default(FX.kt:399)
	at tornadofx.App.start(App.kt:78)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by mysticdrew** [comment]
Sorry, I did not see this, it is fixed with in 1.3
